const {app,BrowserWindow,ipcMain,dialog,shell}=require('electron');
const fs=require('fs'),path=require('path'),crypto=require('crypto'),PDFDocument=require('pdfkit'),ExcelJS=require('exceljs');
let win,session=null; const classes=['PG','Nursery','Jr KG','Sr KG'];
const df=()=>path.join(app.getPath('userData'),'school-data.json');
const dirs=()=>{let b=path.join(app.getPath('documents'),'School Fee Desk');for(let x of ['Invoices','Backups'])fs.mkdirSync(path.join(b,x),{recursive:true});return b};
const fresh=()=>({settings:{schoolName:'My School',schoolAddress:'',schoolPhone:'',currency:'₹',academicYear:'2026-27',receiptPrefix:'SFD',cloudUrl:'https://xtscibvomsurxlmdyhyv.supabase.co',cloudAnonKey:'sb_publishable_gLSNxNqsE_FmORg6izdw9g_kfaY_Ynj',cloudEmail:'',refreshToken:''},auth:{salt:'',hash:''},students:[],payments:[],sync:{lastSyncAt:'',lastError:''}});
function load(){try{return Object.assign(fresh(),JSON.parse(fs.readFileSync(df(),'utf8')))}catch{return fresh()}}
function save(d){fs.mkdirSync(path.dirname(df()),{recursive:true});fs.writeFileSync(df(),JSON.stringify(d,null,2))}
function state(){let d=load(),x=structuredClone(d);x.settings.cloudAnonKey=x.settings.cloudAnonKey?'••••••••':'';x.settings.refreshToken='';x.auth={pinConfigured:!!d.auth.hash};x.cloud={configured:!!(d.settings.cloudUrl&&d.settings.cloudAnonKey),signedIn:!!session,email:d.settings.cloudEmail,lastSyncAt:d.sync.lastSyncAt,lastError:d.sync.lastError};return x}
const hid=(p)=>p+Date.now()+crypto.randomBytes(3).toString('hex'), hp=(p,s)=>crypto.scryptSync(String(p),s,32).toString('hex');
const base=d=>d.settings.cloudUrl.replace(/\/$/,'');
async function api(d,url,opt={}){let r=await fetch(base(d)+url,{...opt,headers:{apikey:d.settings.cloudAnonKey,Authorization:'Bearer '+(session?.access_token||d.settings.cloudAnonKey),'Content-Type':'application/json',...(opt.headers||{})}});let t=await r.text(),j;try{j=t?JSON.parse(t):null}catch{j=t}if(!r.ok)throw Error(j?.message||j?.error_description||t||('Cloud '+r.status));return j}
async function login(d,e,p){session=await api(d,'/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email:e,password:p})});d.settings.cloudEmail=e;d.settings.refreshToken=session.refresh_token||'';save(d)}
async function ensure(d){if(session?.access_token)return true;if(!d.settings.refreshToken)return false;try{session=await api(d,'/auth/v1/token?grant_type=refresh_token',{method:'POST',body:JSON.stringify({refresh_token:d.settings.refreshToken})});d.settings.refreshToken=session.refresh_token||d.settings.refreshToken;save(d);return true}catch{return false}}
async function upsert(d,t,row){if(!await ensure(d))return;let q={...row,user_id:session.user.id};delete q.receiptPath;delete q.publicUrl;await api(d,'/rest/v1/'+t+'?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(q)})}
async function upload(d,p){if(!p.receiptPath||!fs.existsSync(p.receiptPath)||!await ensure(d))return'';let f=session.user.id+'/'+p.receiptNo.replace(/[^\w-]/g,'_')+'.pdf',r=await fetch(base(d)+'/storage/v1/object/invoices/'+f,{method:'POST',headers:{apikey:d.settings.cloudAnonKey,Authorization:'Bearer '+session.access_token,'Content-Type':'application/pdf','x-upsert':'true'},body:fs.readFileSync(p.receiptPath)});if(!r.ok)throw Error(await r.text());return base(d)+'/storage/v1/object/public/invoices/'+f}
async function sync(d){if(!d.settings.cloudUrl||!d.settings.cloudAnonKey)throw Error('Configure cloud first.');if(!await ensure(d))throw Error('Sign in first.');for(let s of d.students)await upsert(d,'students',s);for(let p of d.payments){await upsert(d,'payments',p);if(!p.publicUrl)try{p.publicUrl=await upload(d,p)}catch{}}let [ss,pp]=await Promise.all([api(d,'/rest/v1/students?select=*'),api(d,'/rest/v1/payments?select=*')]);let merge=(local,remote)=>{let m=new Map(local.map(x=>[x.id,x]));for(let x of remote){delete x.user_id;m.set(x.id,{...m.get(x.id),...x})}return [...m.values()]};d.students=merge(d.students,ss);d.payments=merge(d.payments,pp);d.sync.lastSyncAt=new Date().toISOString();d.sync.lastError='';save(d);return d.sync}
function receiptNo(d,p){let y=new Date(p.paymentDate).getFullYear(),c=p.className.replace(/\s/g,'').toUpperCase(),n=d.payments.filter(x=>x.className===p.className&&new Date(x.paymentDate).getFullYear()===y).length+1;return (d.settings.receiptPrefix||'SFD')+'-'+c+'-'+y+'-'+String(n).padStart(4,'0')}
function pdf(d,p,s){return new Promise((ok,no)=>{let f=path.join(dirs(),'Invoices',p.receiptNo+'.pdf'),doc=new PDFDocument({margin:50}),st=fs.createWriteStream(f);doc.pipe(st);doc.font('Helvetica-Bold').fontSize(22).text(d.settings.schoolName,{align:'center'});if(d.settings.schoolAddress)doc.font('Helvetica').fontSize(10).text(d.settings.schoolAddress,{align:'center'});doc.moveDown().font('Helvetica-Bold').fontSize(16).text('PAYMENT RECEIPT',{align:'center'}).moveDown();for(let [a,b] of [['Receipt No.',p.receiptNo],['Date',p.paymentDate],['Student',s.name],['Admission No.',s.admissionNo||'-'],['Class',s.className],['Parent',s.parentName||'-'],['Fee Type',p.feeType],['Fee Month',p.feeMonth||'-'],['Amount Paid',(d.settings.currency||'₹')+Number(p.amount).toLocaleString('en-IN')],['Payment Method',p.method],['Reference',p.referenceNo||'-']])doc.font('Helvetica-Bold').fontSize(11).text(a+' ',{continued:true}).font('Helvetica').text(String(b)).moveDown(.3);doc.moveDown().text('Payment received. Thank you.',{align:'center'}).fontSize(9).text('Computer-generated receipt.',{align:'center'});doc.end();st.on('finish',()=>ok(f));st.on('error',no)})}
async function excel(d){let wb=new ExcelJS.Workbook(),sm=Object.fromEntries(d.students.map(s=>[s.id,s]));function sheet(n,rows){let w=wb.addWorksheet(n);w.columns=[['Date','paymentDate',14],['Receipt','receiptNo',24],['Admission','admission',14],['Student','student',22],['Class','className',12],['Fee Type','feeType',16],['Fee Month','feeMonth',14],['Amount','amount',12],['Method','method',14]].map(([header,key,width])=>({header,key,width}));for(let p of rows){let s=sm[p.studentId]||{};w.addRow({...p,admission:s.admissionNo||'',student:s.name||'',amount:Number(p.amount)})}w.getRow(1).font={bold:true};w.views=[{state:'frozen',ySplit:1}]}sheet('All Payments',d.payments);for(let c of classes)sheet(c,d.payments.filter(p=>p.className===c));let now=new Date().toISOString().slice(0,7),pend=d.students.filter(s=>s.active!==false&&!d.payments.some(p=>p.studentId===s.id&&p.feeType==='Monthly Fee'&&p.feeMonth===now)),w=wb.addWorksheet('Pending Fees');w.addRow(['Admission','Student','Class','Parent','Phone','Monthly Fee']);pend.forEach(s=>w.addRow([s.admissionNo,s.name,s.className,s.parentName,s.phone,Number(s.monthlyFee||0)]));w.getRow(1).font={bold:true};let r=await dialog.showSaveDialog({defaultPath:path.join(app.getPath('documents'),'School-Fee-Desk-'+now+'.xlsx'),filters:[{name:'Excel',extensions:['xlsx']}]});if(r.canceled)return null;await wb.xlsx.writeFile(r.filePath);return r.filePath}
ipcMain.handle('app:state',()=>state());
ipcMain.handle('auth:setupPin',(_,p)=>{if(!/^\d{4,8}$/.test(p))throw Error('Use a 4-8 digit PIN.');let d=load();d.auth.salt=crypto.randomBytes(16).toString('hex');d.auth.hash=hp(p,d.auth.salt);save(d);return true});
ipcMain.handle('auth:verifyPin',(_,p)=>{let d=load();return !!d.auth.hash&&hp(p,d.auth.salt)===d.auth.hash});
ipcMain.handle('auth:changePin',(_,a,b)=>{let d=load();if(hp(a,d.auth.salt)!==d.auth.hash)throw Error('Current PIN is incorrect.');if(!/^\d{4,8}$/.test(b))throw Error('Use a 4-8 digit PIN.');d.auth.salt=crypto.randomBytes(16).toString('hex');d.auth.hash=hp(b,d.auth.salt);save(d);return true});
ipcMain.handle('settings:save',(_,s)=>{let d=load(),old=d.settings.cloudAnonKey;d.settings={...d.settings,...s};if(s.cloudAnonKey==='••••••••')d.settings.cloudAnonKey=old;save(d);return state()});
ipcMain.handle('cloud:signin',async(_,e,p)=>{let d=load();await login(d,e,p);return state()});ipcMain.handle('cloud:signout',()=>{let d=load();session=null;d.settings.refreshToken='';save(d);return state()});ipcMain.handle('cloud:sync',async()=>{let d=load();await sync(d);return state()});
ipcMain.handle('student:save',async(_,s)=>{let d=load(),x={...s,id:s.id||hid('stu_'),monthlyFee:Number(s.monthlyFee||0),updatedAt:new Date().toISOString()};let i=d.students.findIndex(z=>z.id===x.id);i>=0?d.students[i]=x:d.students.push({...x,createdAt:x.updatedAt});save(d);if(session)try{await upsert(d,'students',x)}catch{}return state()});
ipcMain.handle('student:delete',async(_,id)=>{let d=load();if(d.payments.some(p=>p.studentId===id))throw Error('Student has payment history. Mark inactive instead.');d.students=d.students.filter(s=>s.id!==id);save(d);if(session)try{await api(d,'/rest/v1/students?id=eq.'+encodeURIComponent(id),{method:'DELETE'})}catch{}return state()});
ipcMain.handle('payment:record',async(_,q)=>{let d=load(),s=d.students.find(x=>x.id===q.studentId);if(!s)throw Error('Select a student.');if(!(Number(q.amount)>0))throw Error('Enter a valid amount.');let p={...q,id:hid('pay_'),className:s.className,amount:Number(q.amount),receiptNo:'',createdAt:new Date().toISOString()};p.receiptNo=receiptNo(d,p);p.receiptPath=await pdf(d,p,s);d.payments.push(p);save(d);if(session)try{await upsert(d,'payments',p);p.publicUrl=await upload(d,p);save(d)}catch{}return {state:state(),payment:p}});
ipcMain.handle('excel:export',async()=>excel(load()));ipcMain.handle('backup:create',()=>{let d=load(),f=path.join(dirs(),'Backups','backup-'+new Date().toISOString().replace(/[:.]/g,'-')+'.json');fs.writeFileSync(f,JSON.stringify(d,null,2));return f});ipcMain.handle('backup:openFolder',()=>shell.openPath(path.join(dirs(),'Backups')));ipcMain.handle('folder:invoices',()=>shell.openPath(path.join(dirs(),'Invoices')));ipcMain.handle('receipt:open',(_,p)=>shell.openPath(p));ipcMain.handle('whatsapp:open',(_,p)=>{let d=load(),s=d.students.find(x=>x.id===p.studentId),phone=(s?.phone||'').replace(/\D/g,''),msg='Dear '+(s?.parentName||'Parent')+', we received '+(d.settings.currency||'₹')+Number(p.amount).toLocaleString('en-IN')+' for '+(s?.name||'student')+' ('+p.feeType+(p.feeMonth?' - '+p.feeMonth:'')+'). Receipt: '+p.receiptNo+(p.publicUrl?' '+p.publicUrl:'')+'. Thank you, '+d.settings.schoolName;shell.openExternal('https://wa.me/'+phone+'?text='+encodeURIComponent(msg))});
function create(){win=new BrowserWindow({width:1280,height:820,minWidth:1000,minHeight:650,webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,nodeIntegration:false}});win.loadFile(path.join(__dirname,'renderer','index.html'))}
app.whenReady().then(create);app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit()});app.on('activate',()=>{if(BrowserWindow.getAllWindows().length===0)create()});