const {app,BrowserWindow,ipcMain,dialog,shell}=require('electron');
const fs=require('fs'),path=require('path'),crypto=require('crypto'),PDFDocument=require('pdfkit'),ExcelJS=require('exceljs');
let win,session=null,membership=null; const classes=['PG','Nursery','Jr KG','Sr KG'];
const df=()=>path.join(app.getPath('userData'),'school-data.json');
const dirs=()=>{let b=path.join(app.getPath('documents'),'School Fee Desk');for(let x of ['Invoices','Backups'])fs.mkdirSync(path.join(b,x),{recursive:true});return b};
const fresh=()=>({settings:{schoolName:'My School',schoolAddress:'',schoolPhone:'',currency:'₹',academicYear:'2026-27',receiptPrefix:'SFD',receiptFooter:'Thank you for your payment. Please keep this receipt for your records.',whatsappTemplate:'Dear {parent},\n\nWe have received {amount} towards {student} ({class}) for {feeType}{feeMonthLine}.\n\nReceipt No: {receiptNo}\nPayment Date: {paymentDate}\nPayment Method: {method}\n\nView / download receipt: {receiptUrl}\n\nThank you,\n{schoolName}',cloudUrl:'https://xtscibvomsurxlmdyhyv.supabase.co',cloudAnonKey:'sb_publishable_gLSNxNqsE_FmORg6izdw9g_kfaY_Ynj',cloudEmail:'',refreshToken:''},auth:{salt:'',hash:''},students:[],payments:[],expenses:[],inventoryItems:[],inventoryOrders:[],studentInventory:[],sync:{lastSyncAt:'',lastError:''}});
function load(){try{return Object.assign(fresh(),JSON.parse(fs.readFileSync(df(),'utf8')))}catch{return fresh()}}
function save(d){fs.mkdirSync(path.dirname(df()),{recursive:true});fs.writeFileSync(df(),JSON.stringify(d,null,2))}
function state(){let d=load(),x=structuredClone(d);x.settings.cloudAnonKey=x.settings.cloudAnonKey?'••••••••':'';x.settings.refreshToken='';x.auth={pinConfigured:!!d.auth.hash};x.cloud={configured:!!(d.settings.cloudUrl&&d.settings.cloudAnonKey),signedIn:!!session,email:d.settings.cloudEmail,lastSyncAt:d.sync.lastSyncAt,lastError:d.sync.lastError,role:membership?.role||'',schoolId:membership?.school_id||''};return x}
const hid=(p)=>p+Date.now()+crypto.randomBytes(3).toString('hex'), hp=(p,s)=>crypto.scryptSync(String(p),s,32).toString('hex');
const base=d=>d.settings.cloudUrl.replace(/\/$/,'');
async function api(d,url,opt={}){let r=await fetch(base(d)+url,{...opt,headers:{apikey:d.settings.cloudAnonKey,Authorization:'Bearer '+(session?.access_token||d.settings.cloudAnonKey),'Content-Type':'application/json',...(opt.headers||{})}});let t=await r.text(),j;try{j=t?JSON.parse(t):null}catch{j=t}if(!r.ok)throw Error(j?.message||j?.error_description||t||('Cloud '+r.status));return j}
async function loadMembership(d){if(!session?.user?.id)return null;let rows=await api(d,'/rest/v1/school_memberships?select=school_id,role&user_id=eq.'+encodeURIComponent(session.user.id));membership=rows?.[0]||null;if(!membership)throw Error('This login is not assigned to the school.');return membership}
async function login(d,e,p){session=await api(d,'/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email:e,password:p})});d.settings.cloudEmail=e;d.settings.refreshToken=session.refresh_token||'';save(d);await loadMembership(d);try{await sync(d)}catch{}}
async function ensure(d){if(session?.access_token){if(!membership)await loadMembership(d);return true}if(!d.settings.refreshToken)return false;try{session=await api(d,'/auth/v1/token?grant_type=refresh_token',{method:'POST',body:JSON.stringify({refresh_token:d.settings.refreshToken})});d.settings.refreshToken=session.refresh_token||d.settings.refreshToken;save(d);await loadMembership(d);return true}catch{return false}}
async function upsert(d,t,row){if(!await ensure(d))return;if(membership.role==='general'&&(t==='students'||t==='payments'))throw Error('General login is view-only for students and fee payments.');let q={...row,school_id:membership.school_id};if(t==='students'||t==='payments')q.user_id=row.user_id||session.user.id;if(t==='payments')q.recorded_by=row.recorded_by||session.user.id;if(['expenses','inventory_items','inventory_orders','student_inventory'].includes(t))q.created_by=row.created_by||session.user.id;delete q.receiptPath;delete q.publicUrl;delete q.localReceiptPath;await api(d,'/rest/v1/'+t+'?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(q)})}
async function upload(d,p){if(!p.receiptPath||!fs.existsSync(p.receiptPath)||!await ensure(d))return'';let f=membership.school_id+'/'+p.receiptNo.replace(/[^\w-]/g,'_')+'.pdf',r=await fetch(base(d)+'/storage/v1/object/invoices/'+f,{method:'POST',headers:{apikey:d.settings.cloudAnonKey,Authorization:'Bearer '+session.access_token,'Content-Type':'application/pdf','x-upsert':'true'},body:fs.readFileSync(p.receiptPath)});if(!r.ok)throw Error(await r.text());return base(d)+'/storage/v1/object/public/invoices/'+f}
async function sync(d){if(!d.settings.cloudUrl||!d.settings.cloudAnonKey)throw Error('Configure cloud first.');if(!await ensure(d))throw Error('Sign in first.');if(membership.role!=='general'){for(let s of d.students)await upsert(d,'students',s);for(let p of d.payments){await upsert(d,'payments',p);if(!p.publicUrl)try{p.publicUrl=await upload(d,p)}catch{}}}for(let x of d.expenses)await upsert(d,'expenses',x);for(let x of d.inventoryItems)await upsert(d,'inventory_items',x);for(let x of d.inventoryOrders)await upsert(d,'inventory_orders',x);for(let x of d.studentInventory)await upsert(d,'student_inventory',x);let [ss,pp,ee,ii,io,si,sch]=await Promise.all([api(d,'/rest/v1/students?select=*'),api(d,'/rest/v1/payments?select=*'),api(d,'/rest/v1/expenses?select=*'),api(d,'/rest/v1/inventory_items?select=*'),api(d,'/rest/v1/inventory_orders?select=*'),api(d,'/rest/v1/student_inventory?select=*'),api(d,'/rest/v1/schools?select=id,name,config&id=eq.'+encodeURIComponent(membership.school_id))]);let merge=(local,remote)=>{let m=new Map(local.map(x=>[x.id,x]));for(let x of remote){delete x.user_id;m.set(x.id,{...m.get(x.id),...x})}return [...m.values()]};d.students=merge(d.students,ss);d.payments=merge(d.payments,pp);d.expenses=merge(d.expenses,ee);d.inventoryItems=merge(d.inventoryItems,ii);d.inventoryOrders=merge(d.inventoryOrders,io);d.studentInventory=merge(d.studentInventory,si);if(sch?.[0]?.config)d.settings={...d.settings,...sch[0].config};d.sync.lastSyncAt=new Date().toISOString();d.sync.lastError='';save(d);return d.sync}
function receiptNo(d,p){let y=new Date(p.paymentDate).getFullYear(),c=p.className.replace(/\s/g,'').toUpperCase(),n=d.payments.filter(x=>x.className===p.className&&new Date(x.paymentDate).getFullYear()===y).length+1;return (d.settings.receiptPrefix||'SFD')+'-'+c+'-'+y+'-'+String(n).padStart(4,'0')}
function pdf(d,p,s){return new Promise((ok,no)=>{let f=path.join(dirs(),'Invoices',p.receiptNo+'.pdf'),doc=new PDFDocument({margin:46,size:'A4'}),st=fs.createWriteStream(f);doc.pipe(st);doc.font('Helvetica-Bold').fontSize(24).text(d.settings.schoolName,{align:'center'});if(d.settings.schoolAddress)doc.font('Helvetica').fontSize(10).text(d.settings.schoolAddress,{align:'center'});if(d.settings.schoolPhone)doc.text('Phone: '+d.settings.schoolPhone,{align:'center'});doc.moveDown(.8);doc.moveTo(46,doc.y).lineTo(549,doc.y).stroke();doc.moveDown(.8);doc.font('Helvetica-Bold').fontSize(17).text('PAYMENT RECEIPT',{align:'center'});doc.moveDown(.8);doc.fontSize(11);let left=56,right=310,y=doc.y;doc.font('Helvetica-Bold').text('Receipt No.',left,y).font('Helvetica').text(p.receiptNo,left+90,y);doc.font('Helvetica-Bold').text('Payment Date',right,y).font('Helvetica').text(p.paymentDate,right+95,y);doc.moveDown(1.5);y=doc.y;for(let [a,b] of [['Student',s.name],['Admission No.',s.admissionNo||'-'],['Class',s.className],['Parent / Guardian',s.parentName||'-']]){doc.font('Helvetica-Bold').text(a,left,y,{width:120}).font('Helvetica').text(String(b),180,y,{width:350});y+=24}doc.y=y+6;doc.rect(56,doc.y,483,30).fillAndStroke('#f4f6fa','#d9dee8');doc.fillColor('#18243a').font('Helvetica-Bold').text('Fee Description',68,doc.y-21).text('Amount',440,doc.y-21);let feeDesc=p.feeType+(p.feeMonth?' - '+p.feeMonth:'');doc.rect(56,doc.y+2,483,42).stroke('#d9dee8');doc.font('Helvetica').text(feeDesc,68,doc.y+16,{width:340}).font('Helvetica-Bold').text((d.settings.currency||'₹')+Number(p.amount).toLocaleString('en-IN'),430,doc.y+16,{width:95,align:'right'});doc.moveDown(4.3);for(let [a,b] of [['Payment Method',p.method],['Reference No.',p.referenceNo||'-']])doc.font('Helvetica-Bold').text(a+': ',56,doc.y,{continued:true}).font('Helvetica').text(String(b));doc.moveDown(1.2);doc.moveTo(56,doc.y).lineTo(539,doc.y).stroke();doc.moveDown(.8);doc.font('Helvetica').fontSize(10).text(d.settings.receiptFooter||'Thank you for your payment.',{align:'center'});doc.moveDown(.4).fontSize(8).fillColor('#6b7280').text('This is a computer-generated receipt and does not require a signature.',{align:'center'});doc.end();st.on('finish',()=>ok(f));st.on('error',no)})}
async function excel(d){let wb=new ExcelJS.Workbook(),sm=Object.fromEntries(d.students.map(s=>[s.id,s]));function sheet(n,rows){let w=wb.addWorksheet(n);w.columns=[['Date','paymentDate',14],['Receipt','receiptNo',24],['Admission','admission',14],['Student','student',22],['Class','className',12],['Fee Type','feeType',16],['Fee Month','feeMonth',14],['Amount','amount',12],['Method','method',14]].map(([header,key,width])=>({header,key,width}));for(let p of rows){let s=sm[p.studentId]||{};w.addRow({...p,admission:s.admissionNo||'',student:s.name||'',amount:Number(p.amount)})}w.getRow(1).font={bold:true};w.views=[{state:'frozen',ySplit:1}]}sheet('All Payments',d.payments);for(let c of classes)sheet(c,d.payments.filter(p=>p.className===c));let now=new Date().toISOString().slice(0,7),pend=d.students.filter(s=>s.active!==false&&!d.payments.some(p=>p.studentId===s.id&&p.feeType==='Monthly Fee'&&p.feeMonth===now)),w=wb.addWorksheet('Pending Fees');w.addRow(['Admission','Student','Class','Parent','Phone','Monthly Fee']);pend.forEach(s=>w.addRow([s.admissionNo,s.name,s.className,s.parentName,s.phone,Number(s.monthlyFee||0)]));w.getRow(1).font={bold:true};let r=await dialog.showSaveDialog({defaultPath:path.join(app.getPath('documents'),'School-Fee-Desk-'+now+'.xlsx'),filters:[{name:'Excel',extensions:['xlsx']}]});if(r.canceled)return null;await wb.xlsx.writeFile(r.filePath);return r.filePath}
ipcMain.handle('app:state',()=>state());
ipcMain.handle('auth:setupPin',(_,p)=>{if(!/^\d{4,8}$/.test(p))throw Error('Use a 4-8 digit PIN.');let d=load();d.auth.salt=crypto.randomBytes(16).toString('hex');d.auth.hash=hp(p,d.auth.salt);save(d);return true});
ipcMain.handle('auth:verifyPin',(_,p)=>{let d=load();return !!d.auth.hash&&hp(p,d.auth.salt)===d.auth.hash});
ipcMain.handle('auth:changePin',(_,a,b)=>{let d=load();if(hp(a,d.auth.salt)!==d.auth.hash)throw Error('Current PIN is incorrect.');if(!/^\d{4,8}$/.test(b))throw Error('Use a 4-8 digit PIN.');d.auth.salt=crypto.randomBytes(16).toString('hex');d.auth.hash=hp(b,d.auth.salt);save(d);return true});
ipcMain.handle('settings:save',async(_,s)=>{let d=load(),old=d.settings.cloudAnonKey;d.settings={...d.settings,...s};if(s.cloudAnonKey==='••••••••')d.settings.cloudAnonKey=old;save(d);if(await ensure(d)&&membership.role==='admin'){let cfg={schoolName:d.settings.schoolName,schoolAddress:d.settings.schoolAddress,schoolPhone:d.settings.schoolPhone,currency:d.settings.currency,academicYear:d.settings.academicYear,receiptPrefix:d.settings.receiptPrefix,receiptFooter:d.settings.receiptFooter,whatsappTemplate:d.settings.whatsappTemplate};await api(d,'/rest/v1/schools?id=eq.'+encodeURIComponent(membership.school_id),{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({name:d.settings.schoolName,config:cfg})})}return state()});
ipcMain.handle('cloud:signin',async(_,e,p)=>{let d=load();await login(d,e,p);return state()});ipcMain.handle('cloud:signout',()=>{let d=load();session=null;membership=null;d.settings.refreshToken='';save(d);return state()});ipcMain.handle('cloud:sync',async()=>{let d=load();await sync(d);return state()});
ipcMain.handle('student:save',async(_,s)=>{let d=load();if(await ensure(d)&&membership.role==='general')throw Error('General login is view-only.');let x={...s,id:s.id||hid('stu_'),monthlyFee:Number(s.monthlyFee||0),updatedAt:new Date().toISOString()};let i=d.students.findIndex(z=>z.id===x.id);i>=0?d.students[i]=x:d.students.push({...x,createdAt:x.updatedAt});save(d);if(session)try{await upsert(d,'students',x)}catch{}return state()});
ipcMain.handle('student:delete',async(_,id)=>{let d=load();if(!await ensure(d)||membership.role!=='admin')throw Error('Only Admin can delete students.');if(d.payments.some(p=>p.studentId===id))throw Error('Student has payment history. Mark inactive instead.');d.students=d.students.filter(s=>s.id!==id);save(d);if(session)try{await api(d,'/rest/v1/students?id=eq.'+encodeURIComponent(id),{method:'DELETE'})}catch{}return state()});
ipcMain.handle('payment:record',async(_,q)=>{let d=load();if(await ensure(d)&&membership.role==='general')throw Error('General login is view-only.');let s=d.students.find(x=>x.id===q.studentId);if(!s)throw Error('Select a student.');if(!(Number(q.amount)>0))throw Error('Enter a valid amount.');let p={...q,id:hid('pay_'),className:s.className,amount:Number(q.amount),receiptNo:'',createdAt:new Date().toISOString()};p.receiptNo=receiptNo(d,p);p.receiptPath=await pdf(d,p,s);d.payments.push(p);save(d);if(session)try{await upsert(d,'payments',p);p.publicUrl=await upload(d,p);save(d)}catch{}return {state:state(),payment:p}});


async function uploadExpenseReceipt(d,localPath,expenseId){
  if(!localPath||!fs.existsSync(localPath)||!await ensure(d))return '';
  let ext=path.extname(localPath)||'.bin',obj=membership.school_id+'/'+expenseId+ext;
  let r=await fetch(base(d)+'/storage/v1/object/expense-receipts/'+obj,{method:'POST',headers:{apikey:d.settings.cloudAnonKey,Authorization:'Bearer '+session.access_token,'Content-Type':'application/octet-stream','x-upsert':'true'},body:fs.readFileSync(localPath)});
  if(!r.ok)throw Error(await r.text());return obj;
}
ipcMain.handle('expense:chooseReceipt',async()=>{let r=await dialog.showOpenDialog({properties:['openFile'],filters:[{name:'Receipt',extensions:['pdf','png','jpg','jpeg','webp']}]});return r.canceled?'':r.filePaths[0]});
ipcMain.handle('expense:save',async(_,q)=>{let d=load();if(!await ensure(d))throw Error('Cloud login required.');let x={...q,id:q.id||hid('exp_'),amount:Number(q.amount||0),created_by:q.created_by||session.user.id,created_at:q.created_at||new Date().toISOString(),updated_at:new Date().toISOString()};if(!(x.amount>=0)||!x.expense_date||!x.category||!x.description)throw Error('Date, category, description and amount are required.');if(q.localReceiptPath){x.receipt_path=await uploadExpenseReceipt(d,q.localReceiptPath,x.id);x.localReceiptPath=q.localReceiptPath}let i=d.expenses.findIndex(z=>z.id===x.id);i>=0?d.expenses[i]=x:d.expenses.push(x);save(d);await upsert(d,'expenses',x);return state()});
ipcMain.handle('expense:openReceipt',async(_,receiptPath)=>{let d=load();if(!receiptPath||!await ensure(d))return;let r=await fetch(base(d)+'/storage/v1/object/authenticated/expense-receipts/'+receiptPath,{headers:{apikey:d.settings.cloudAnonKey,Authorization:'Bearer '+session.access_token}});if(!r.ok)throw Error('Unable to open expense receipt.');let buf=Buffer.from(await r.arrayBuffer()),ext=path.extname(receiptPath)||'.bin',tmp=path.join(app.getPath('temp'),'school-expense-'+Date.now()+ext);fs.writeFileSync(tmp,buf);return shell.openPath(tmp)});
ipcMain.handle('inventory:itemSave',async(_,q)=>{let d=load();if(!await ensure(d))throw Error('Cloud login required.');let x={...q,id:q.id||hid('itm_'),stock_on_hand:Number(q.stock_on_hand||0),ordered_pending:Number(q.ordered_pending||0),reorder_level:Number(q.reorder_level||0),created_by:q.created_by||session.user.id,created_at:q.created_at||new Date().toISOString(),updated_at:new Date().toISOString()};if(!x.name||!x.item_type)throw Error('Item type and name are required.');let i=d.inventoryItems.findIndex(z=>z.id===x.id);i>=0?d.inventoryItems[i]=x:d.inventoryItems.push(x);save(d);await upsert(d,'inventory_items',x);return state()});
ipcMain.handle('inventory:orderSave',async(_,q)=>{let d=load();if(!await ensure(d))throw Error('Cloud login required.');let item=d.inventoryItems.find(x=>x.id===q.item_id);if(!item)throw Error('Select an inventory item.');let x={...q,id:q.id||hid('ord_'),quantity:Number(q.quantity||0),received_quantity:Number(q.received_quantity||0),status:q.status||'Ordered',created_by:q.created_by||session.user.id,created_at:q.created_at||new Date().toISOString(),updated_at:new Date().toISOString()};if(x.quantity<=0)throw Error('Order quantity must be greater than 0.');let i=d.inventoryOrders.findIndex(z=>z.id===x.id);i>=0?d.inventoryOrders[i]=x:d.inventoryOrders.push(x);item.ordered_pending=d.inventoryOrders.filter(o=>o.item_id===item.id&&o.status!=='Received'&&o.status!=='Cancelled').reduce((a,o)=>a+Math.max(0,Number(o.quantity)-Number(o.received_quantity||0)),0);save(d);await upsert(d,'inventory_orders',x);await upsert(d,'inventory_items',item);return state()});
ipcMain.handle('inventory:receiveOrder',async(_,id,qty)=>{let d=load();if(!await ensure(d))throw Error('Cloud login required.');let o=d.inventoryOrders.find(x=>x.id===id),item=d.inventoryItems.find(x=>x.id===o?.item_id);if(!o||!item)throw Error('Order not found.');qty=Number(qty||0);let remaining=Number(o.quantity)-Number(o.received_quantity||0);if(qty<=0||qty>remaining)throw Error('Invalid received quantity.');o.received_quantity=Number(o.received_quantity||0)+qty;o.status=o.received_quantity>=o.quantity?'Received':'Partially Received';o.updated_at=new Date().toISOString();item.stock_on_hand=Number(item.stock_on_hand||0)+qty;item.ordered_pending=Math.max(0,Number(item.ordered_pending||0)-qty);item.updated_at=new Date().toISOString();save(d);await upsert(d,'inventory_orders',o);await upsert(d,'inventory_items',item);return state()});
ipcMain.handle('inventory:studentSave',async(_,q)=>{let d=load();if(!await ensure(d))throw Error('Cloud login required.');let item=d.inventoryItems.find(x=>x.id===q.item_id),stu=d.students.find(x=>x.id===q.student_id);if(!item||!stu)throw Error('Select student and item.');let existing=d.studentInventory.find(x=>x.student_id===q.student_id&&x.item_id===q.item_id),x={...existing,...q,id:existing?.id||q.id||hid('sti_'),quantity:Number(q.quantity||1),created_by:existing?.created_by||session.user.id,created_at:existing?.created_at||new Date().toISOString(),updated_at:new Date().toISOString()};if(x.status==='Issued'&&existing?.status!=='Issued'){if(Number(item.stock_on_hand)<x.quantity)throw Error('Not enough stock to issue this item.');item.stock_on_hand=Number(item.stock_on_hand)-x.quantity;x.issued_at=q.issued_at||new Date().toISOString().slice(0,10);await upsert(d,'inventory_items',item)}if(existing?.status==='Issued'&&x.status!=='Issued'){item.stock_on_hand=Number(item.stock_on_hand)+Number(existing.quantity||1);await upsert(d,'inventory_items',item)}let i=d.studentInventory.findIndex(z=>z.id===x.id);i>=0?d.studentInventory[i]=x:d.studentInventory.push(x);save(d);await upsert(d,'student_inventory',x);return state()});

ipcMain.handle('user:create',async(_,u)=>{let d=load();if(!await ensure(d)||membership.role!=='admin')throw Error('Only Admin can create users.');let r=await fetch(base(d)+'/functions/v1/manage-school-user',{method:'POST',headers:{apikey:d.settings.cloudAnonKey,Authorization:'Bearer '+session.access_token,'Content-Type':'application/json'},body:JSON.stringify(u)});let j=await r.json();if(!r.ok||j.error)throw Error(j.error||'Unable to create user');return j});
ipcMain.handle('excel:export',async()=>excel(load()));ipcMain.handle('backup:create',()=>{let d=load(),f=path.join(dirs(),'Backups','backup-'+new Date().toISOString().replace(/[:.]/g,'-')+'.json');fs.writeFileSync(f,JSON.stringify(d,null,2));return f});ipcMain.handle('backup:openFolder',()=>shell.openPath(path.join(dirs(),'Backups')));ipcMain.handle('folder:invoices',()=>shell.openPath(path.join(dirs(),'Invoices')));ipcMain.handle('receipt:open',(_,p)=>shell.openPath(p));ipcMain.handle('whatsapp:open',(_,p)=>{let d=load(),s=d.students.find(x=>x.id===p.studentId),phone=(s?.phone||'').replace(/\D/g,''),tpl=d.settings.whatsappTemplate||'Dear {parent}, we received {amount} for {student}. Receipt: {receiptUrl}',vals={parent:s?.parentName||'Parent',student:s?.name||'student',class:s?.className||'',amount:(d.settings.currency||'₹')+Number(p.amount).toLocaleString('en-IN'),feeType:p.feeType||'',feeMonth:p.feeMonth||'',feeMonthLine:p.feeMonth?' for '+p.feeMonth:'',receiptNo:p.receiptNo||'',paymentDate:p.paymentDate||'',method:p.method||'',receiptUrl:p.publicUrl||'Receipt PDF available from the school',schoolName:d.settings.schoolName||'School'},msg=tpl.replace(/\{(\w+)\}/g,(_,k)=>vals[k]??'');shell.openExternal('https://wa.me/'+phone+'?text='+encodeURIComponent(msg))});
function create(){win=new BrowserWindow({width:1280,height:820,minWidth:1000,minHeight:650,webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,nodeIntegration:false}});win.loadFile(path.join(__dirname,'renderer','index.html'))}
app.whenReady().then(async()=>{let d=load();try{if(await ensure(d))await sync(d)}catch{}create()});app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit()});app.on('activate',()=>{if(BrowserWindow.getAllWindows().length===0)create()});